#!/usr/bin/env node
/**
 * setup.js — Auto-configure the Vercel frontend
 *
 * Reads API_URL and FRONTEND_URL from environment (or .env file),
 * then writes:
 *   - public/config.js     → runtime config the HTML reads
 *   - vercel.json          → Vercel rewrite rules with correct backend URL
 *
 * Usage:
 *   node setup.js                         # reads from .env
 *   API_URL=https://api.example.com node setup.js
 *   npx vercel env pull .env && node setup.js   # pull from Vercel env then configure
 */

const fs   = require('fs');
const path = require('path');

// ── Load .env if present ──────────────────────────────────────────────────────
const envPath = path.join(__dirname, '.env');
if (fs.existsSync(envPath)) {
  fs.readFileSync(envPath, 'utf8')
    .split('\n')
    .filter(l => l && !l.startsWith('#'))
    .forEach(l => {
      const [k, ...v] = l.split('=');
      if (k && v.length && !process.env[k.trim()]) {
        process.env[k.trim()] = v.join('=').trim().replace(/^["']|["']$/g, '');
      }
    });
}

// ── Resolve config values ─────────────────────────────────────────────────────
const apiUrl      = process.env.API_URL
                 || process.env.NEXT_PUBLIC_API_URL
                 || process.env.BACKEND_URL
                 || 'http://localhost:3001';

const frontendUrl = process.env.FRONTEND_URL
                 || process.env.VERCEL_URL && `https://${process.env.VERCEL_URL}`
                 || 'http://localhost:3000';

console.log('\n📡 Configuring Email Remittance Frontend');
console.log('  API URL:     ', apiUrl);
console.log('  Frontend URL:', frontendUrl);
console.log('');

// ── Write public/config.js ────────────────────────────────────────────────────
// This is loaded by index.html and claim.html at runtime.
// No build step needed — just update this file and redeploy.
const configJs = `// Auto-generated by setup.js — do not edit manually
// Re-run: node setup.js
window.REMITTANCE_CONFIG = {
  apiUrl: "${apiUrl}",
  frontendUrl: "${frontendUrl}",
  generatedAt: "${new Date().toISOString()}",
};
`;

const publicDir = path.join(__dirname, 'public');
if (!fs.existsSync(publicDir)) fs.mkdirSync(publicDir, { recursive: true });
fs.writeFileSync(path.join(publicDir, 'config.js'), configJs);
console.log('✅ public/config.js written');

// ── Write vercel.json ─────────────────────────────────────────────────────────
const vercelJson = {
  rewrites: [
    {
      source: '/api/:path*',
      destination: `${apiUrl}/api/:path*`,
    },
    {
      source: '/claim/:token',
      destination: '/claim.html',
    },
  ],
  headers: [
    {
      source: '/(.*)',
      headers: [
        { key: 'X-Content-Type-Options', value: 'nosniff' },
      ],
    },
  ],
};

fs.writeFileSync(
  path.join(__dirname, 'vercel.json'),
  JSON.stringify(vercelJson, null, 2) + '\n'
);
console.log('✅ vercel.json written');

// ── Write .env.local for local dev ────────────────────────────────────────────
const envLocal = `# Auto-generated by setup.js
API_URL=${apiUrl}
FRONTEND_URL=${frontendUrl}
`;
fs.writeFileSync(path.join(__dirname, '.env.local'), envLocal);
console.log('✅ .env.local written');

console.log('\n🚀 Done! Next steps:');
console.log('   Local dev:   npx serve public');
console.log('   Deploy:      npx vercel --prod');
console.log('   Or push to GitHub → Vercel auto-deploys\n');
